### ISSUE TITLE
[UI] Інтерфейс для додавання файлу зі списком розмічених даних

### ISSUE THREAD

**Issue by carerakjan** [carerakjan/goit-telecom-project-group-1#13]
Додати можливість завантажити файл, умовно csv з відповідною структурою (колонками) необхідними для прогнозування на базі натренованої моделі. Зробити можна окремою вкладкою. Зберегти функціонал ТЗ з використанням форми вводу фічей для одного користувача.

**Comment by Ed9uard** [comment]
required_columns = [
                    'id'||'last_name',
                    'is_tv_subscriber',
                    'is_movie_package_subscriber',
                    'subscription_age',
                    'reamining_contract',
                    'download_avg',
                    'upload_avg',
                    'download_over_limit'
                ] обов'язкові стовпці
