### ISSUE TITLE
[DOC] Написати інструкцію користувача

### ISSUE THREAD

**Issue by carerakjan** [carerakjan/goit-telecom-project-group-1#17]

**Comment by VitaliyStyranko** [comment]
commit https://github.com/carerakjan/goit-telecom-project-group-1/commit/57571c90a9c318e9553b678d5df1ac7bcf46e07e

**Comment by VitaliyStyranko** [comment]
added Technical Documentation https://github.com/carerakjan/goit-telecom-project-group-1/commit/a3e47aa8fe410312de442615e5f86e06e2b7e04e

**Comment by VitaliyStyranko** [comment]
Оновив instructions_for_the_user.txt https://github.com/carerakjan/goit-telecom-project-group-1/commit/bc54fabf1d8a02111a91faf554da187ff97a5b81
