### ISSUE TITLE
[UI] Інтерфейс користувача для вводу даних

### ISSUE THREAD

**Issue by carerakjan** [carerakjan/goit-telecom-project-group-1#19]
**Опис:**
Зробити зручну форму вводу даних користовувача

**Зробити:**
* Введення Даних Клієнта: Інтерфейс або процедура для даних нового клієнта.
* Валідація

**Comment by bond1q-ua** [comment]
Додано:

- ще 1 користувач

**Comment by bond1q-ua** [comment]
Додано:
Збереження результатів минулого користувача після предікту для іншого
