### ISSUE TITLE
[UI] Розробка landing page застосунку

### ISSUE THREAD

**Issue by p1gwowa** [carerakjan/goit-telecom-project-group-1#26]

**Comment by p1gwowa** [comment]
Запушив до мастера зміни: Зробив зміни у файлі main.py для запуску застосунку
Додав файли: landing_page.py, session_state.py, logo.png, Instructions_for_the_User.txt(to be changed)
Додав папки: /images, /docs
Можно затестити застосунок тією ж самою командою :)

**Comment by carerakjan** [comment]
commit #77846716
