### ISSUE TITLE
[UI] Доробити кнопка оновити

### ISSUE THREAD

**Issue by carerakjan** [carerakjan/goit-telecom-project-group-1#47]
скинути все на поточній вкладці залиши сессіоне прогнозування якщо поточна вкладка одиночне прогнозування

**Comment by VitaliyStyranko** [comment]
updated side_panel.py https://github.com/carerakjan/goit-telecom-project-group-1/commit/e587019d9dbae9608ec7239eebc04b60b0dd559a
