### ISSUE TITLE
[MODEL] Розробка Моделі: Логістична регресія

### ISSUE THREAD

**Issue by carerakjan** [carerakjan/goit-telecom-project-group-1#6]
**Опис:**
Задача є частиною дослідження вибору оптимальної моделі.

**Зробити:**
* Навчання Моделі: Крос-валідація для параметрів.
* Оцінювання Моделі: Accuracy, Recall, Precision, F1 score

**Comment by VitaliyStyranko** [comment]
added 'logistic_regression_model.ipynb' to notebooks
added 'logistic_regression_model.pkl' to madels

**Comment by VitaliyStyranko** [comment]
https://github.com/carerakjan/goit-telecom-project-group-1/blob/master/project/notebooks/logistic_regression_model.ipynb

**Comment by carerakjan** [comment]
commits 9a7eeaa6, bc74ca02

**Comment by VitaliyStyranko** [comment]
update files  bfd4430d72cc9fa8902f51630faf168124507135, a2a3ce7d711e823eef94103a36cf3778d437bc95

**Comment by VitaliyStyranko** [comment]
commit https://github.com/carerakjan/goit-telecom-project-group-1/commit/d91b11858dbe4f7164133638e5e67658beb66b6b
