### ISSUE TITLE
[UI] одиночне передбачення результат складати в датафрейм замість session_state

### ISSUE THREAD

**Issue by Ed9uard** [carerakjan/goit-telecom-project-group-1#69]
1. змінинти зберігання з сессії до датафрейму (нове передбачення новий рядок в таблиці)
2. додати колонку "модель передбачення"
3. перкласти на укр колонки [churn_category,churn_probability]

**Comment by Ed9uard** [comment]
3 . перкласти на укр колонки [churn_category,churn_probability] зроблю

**Comment by p1gwowa** [comment]
Я взяв переклад і додавання нових колонок на себе, бо інакше попсую логіку

**Comment by p1gwowa** [comment]
Усі три пункти закомітив
